services:
  express-app:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - flagd

  flagd:
    image: ghcr.io/open-feature/flagd:v0.11.2
    command:
      - start
      - --cors-origin
      - '*'
      - --sources
      - '[{"uri":"etc/flagd/flags.flagd.json","provider":"file","selector":"etc/flagd/flags.flagd.json"}]'
    volumes:
      - ./flagd/flags.flagd.json:/etc/flagd/flags.flagd.json
    ports:
      - '8013:8013'
      - '8016:8016'
